version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npx codechecks codechecks.testing.yml
  production:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npx codechecks codechecks.production.yml
workflows:
  version: 2
  test:
    jobs:
      - test
      - production
