version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.12-stretch
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: yarn codechecks
workflows:
  version: 2
  test:
    jobs:
      - test
