version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.13.0
    working_directory: /home/circleci/app
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - run: npx codechecks
workflows:
  version: 2
  test:
    jobs:
      - test
