version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.13.0
    working_directory: /home/circleci/app
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
      - run: yarn cgewecke-cc-testing
workflows:
  version: 2
  test:
    jobs:
      - test
